name: crypto_trading_app
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1


environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_storage: ^2.0.3
  get: ^4.6.5
  http: ^0.13.3
  cached_network_image: ^3.2.1
  shared_preferences: ^2.0.9
  dio: ^4.0.6
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.0.2
  sticky_and_expandable_list: ^1.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env